name: ack-shun-example
run-name: "${{ github.actor }} is testing out GitHub Actions with Teleport"
on: [push]
jobs:
  teleport-demo-ubuntu:
    permissions:
    # The "id-token: write" permission is required or Machine ID will not be
    # able to authenticate with the cluster.
      id-token: write
      contents: read
    # if you added a workflow name in the previous step, make sure you use the same value here
    name: ack-shun-example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Fetch Teleport binaries
      uses: teleport-actions/setup@v1
      with:
        version: 15.1.9
    # server access example
    - name: Fetch credentials using Machine ID
      id: auth
      uses: teleport-actions/auth@v2
      with:
        proxy: csuttles.teleport.sh:443
        token: ack-shun
        # Enable the submission of anonymous usage telemetry. This
        # helps us shape the future development of `tbot`. You can disable this
        # by omitting this.
        anonymous-telemetry: 1
    - name: List nodes (tsh)
      # Enters a command from the cluster, in this case "tsh ls" using Machine
      # ID credentials to list remote SSH nodes.
      run: tsh ls
    - name: Node info
      run: uname -a && cat /etc/issue && cat /etc/debian_release && ip a && free -g && grep -c ^processor /proc/cpuinfo
